### ISSUE TITLE
Cannot cancel password prompt

### ISSUE THREAD

**Issue by johnoscott** [qing3962/password-protection#2]
I think you should be able to close the password prompt when being asked for the password. I was not able to close it without quitting the app on Mac OS.

**Comment by yustarandomname** [comment]
I experience the same issue on my M1 MacBook. Rest of the plugin works as expected

https://github.com/qing3962/password-protection/assets/25432790/b2bdd817-0497-477b-a118-227b1a0ad9c5

**Comment by qing3962** [comment]
This was intentional.  

Once the password prompt modal is opened, I don't want someone who doesn't know the password to be able to go on, Otherwise, it will expose the tree of directory and title of notes.  

Rewind two versions, in the 1.0.9 version, the modal can be closed. If you really mind this feature, please download and use the 1.0.9 version?

**Comment by yustarandomname** [comment]
In that case, would it be more logical to remove the cross/close icon?

**Comment by qing3962** [comment]
I accept your advise, I have remove the close button of verify password modal, please update to the latest vesion.

**Comment by qing3962** [comment]
If the user forget the password, he wouldn't open the Obsidian, so I decide to allow user to close the verify password modal, I update the version again.
