### ISSUE TITLE
A couple of ideas for improving language clarity

### ISSUE THREAD

**Issue by paintedsky** [qing3962/password-protection#6]
Hi Qing, 

First off, I really like this plugin! It's simple, easy to use, and just what I needed. Thanks!

I have a suggestion in regards to the language used by the plugin. I find the usage of the phrases "Open password protection" and "Close password protection" kind of confusing and counterintuitive.

I have come up with some alternative options for phrasing these functions. I think any of these three options will improve the usability of your plugin for native English speakers.

---

Option 1 (preferred):

- Instead of "Open password protection" use "Lock password protection"
- Instead of "Close password protection" use "Unlock password protection"

---

Option 2:

- Instead of "Open password protection" use "Enable password protection"
- Instead of "Close password protection" use "Disable password protection"

---

Option 3:

- Instead of "Open password protection" use "Turn on password protection"
- Instead of "Close password protection" use "Turn off password protection"

---

Thanks again!

**Comment by qing3962** [comment]
Thanks for your advise.
I accept your first option:Instead of "Open password protection" use "Lock password protection"Instead of "Close password protection" use "Unlock password protection"
I will update the version of the plugin today.
Qing Li

----- 原始邮件 -----
发件人：paintedsky ***@***.***>
收件人：qing3962/password-protection ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[qing3962/password-protection] A couple of ideas for improving language clarity (Issue #6)
日期：2023年08月23日 08点29分


Hi Qing,
First off, I really like this plugin! It's simple, easy to use, and just what I needed. Thanks!
I have a suggestion in regards to the language used by the plugin. I find the usage of the phrases "Open password protection" and "Close password protection" kind of confusing and counterintuitive.
I have come up with some alternative options for phrasing these functions. I think any of these three options will improve the usability of your plugin for native English speakers.

Option 1 (preferred):

Instead of "Open password protection" use "Lock password protection"
Instead of "Close password protection" use "Unlock password protection"


Option 2:

Instead of "Open password protection" use "Enable password protection"
Instead of "Close password protection" use "Disable password protection"


Option 3:

Instead of "Open password protection" use "Turn on password protection"
Instead of "Close password protection" use "Turn off password protection"


Thanks again!

**Comment by qing3962** [comment]
Thanks for your advise.  

I accept your first option:
- Instead of "Open password protection" use "Lock password protection"  
- Instead of "Close password protection" use "Unlock password protection"  

I will update the version of the plugin today.

**Comment by qing3962** [comment]
Done, the new version is 1.1.15.

**Comment by paintedsky** [comment]
Awesome, thanks! I updated earlier today and it looks great.
